services:
  postgres:
    image: postgres:17-alpine
    container_name: munshi-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: munshi-admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: munshi-db
    ports:
      - "5432:5432"
    volumes:
      - munshi-data:/var/lib/postgresql/data

volumes:
  munshi-data: